### ISSUE TITLE
Does this work with Firefox 66?

### ISSUE THREAD

**Issue by AndrewJudson** [azappella/webextension-experiment-tags#2]
I'm seeing "browser.extensions.tags is undefined" when I try to test the API

**Comment by azappella** [comment]
Did you try with `browser.experiments.tags` instead of `browser.extensions.tags`? See https://github.com/azappella/webextension-experiment-tags/blob/master/README.md#api

**Comment by AndrewJudson** [comment]
Sorry, I misspelled it, meant experiments. The issue was that this was a release build of Firefox, not developer edition or nightly. I am able to get it working in developer addition debugger, playing with it now. Thanks!

**Comment by azappella** [comment]
Glad it worked! Let me know if you ever build something with it ;)
